name: Генерация отчёта
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Typst
        uses: typst-community/setup-typst@v5

      - name: Set up submodules
        run: git submodule update --init --recursive

      - name: Create export directory
        run: mkdir export

      - name: Compile 'report.typ'
        run: typst compile report/report.typ export/report.pdf --font-path report/fonts

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: export/
